version: '2'

services:
  web:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/lavr
    ports:
      - "8080:80"
    links:
      - app
  app:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/lavr
    links:
      - db
    environment:
      - DB_PORT=3306
      - DB_HOST=db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=lavrApp
    ports:
      - "33061:3306"
