version: '3'

services:
  web:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/lavr
    ports:
      - "8080:80"
    links:
      - app
    networks:
      - local
  app:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/lavr
    links:
      - db
    environment:
      DB_PORT: 3306
      DB_HOST: db
    networks:
      - local
  react:
      build:
        context: react-app
        dockerfile: Dockerfile
      environment:
        - REACT_APP_PORT=3000
      expose:
        - 3000
      volumes:
        - ./react-app/src:/var/www/lavr/react-app/src
        - ./react-app/public:/var/www/lavr/react-app/public
      links:
        - web
      ports:
        - "3000:3000"
      command: npm run start
      networks:
        - local
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: lavrApp
    ports:
      - "3306:3306"
    networks:
      - local
  adminer:
    image: adminer
    restart: always
    environment:
      DOMAIN_NAME: adminer.local
    links:
      - db
    ports:
      - "8088:8080"
    networks:
      - local
#  laravel:
#    build:
#      context: docker/laravel
#      dockerfile: Dockerfile
#    volumes:
#      - ./:/var/www/lavr
#    links:
#      - web
#    command: php artisan migrate
#    networks:
#      - local
networks:
  local:
